# Generated by Django 5.2.17 on 2026-09-07 01:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianKesiapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('fisik', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('teknik', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mental', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vo2max', models.DecimalField(blank=True, decimal_places=1, help_text='Contoh: 45.5 (ml/kg/min). Boleh kosong bila belum diukur.', max_digits=4, null=True)),
                ('berat_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tinggi_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('kehadiran', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alfa', 'Alfa/Tanpa Keterangan')], default='hadir', max_length=10)),
                ('ada_cedera', models.BooleanField(default=False)),
                ('keterangan_cedera', models.CharField(blank=True, max_length=255)),
                ('catatan_pelatih', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='atlets.atletprofile')),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilaian_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penilaian Kesiapan',
                'verbose_name_plural': 'Penilaian Kesiapan',
                'ordering': ['-tanggal'],
                'constraints': [models.UniqueConstraint(fields=('atlet', 'tanggal'), name='uniq_penilaian_atlet_tanggal')],
            },
        ),
    ]
