# Generated by Django 5.2.17 on 2026-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jurnalis_dokumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pelatih', 'Pelatih'), ('atlet', 'Atlet/Anggota')], default='atlet', max_length=10),
        ),
    ]
