# Generated by Django 5.2.17 on 2026-09-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('kategori', models.CharField(choices=[('umum', 'Umum'), ('latihan', 'Latihan'), ('prestasi', 'Prestasi'), ('event', 'Event'), ('pengumuman', 'Pengumuman')], default='umum', max_length=15)),
                ('ringkasan', models.CharField(blank=True, help_text='Tampil di kartu & landing (maks 300).', max_length=300)),
                ('konten', models.TextField(help_text='Isi berita — gunakan paragraf, boleh line breaks.')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Tampilkan publik')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured di landing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'ordering': ['-created_at'],
            },
        ),
    ]
