# Generated by Django 5.2.17 on 2026-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(blank=True, max_length=150)),
                ('pesan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='berita',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Jumlah dilihat (auto increment saat detail dibuka).'),
        ),
        migrations.AlterField(
            model_name='berita',
            name='konten',
            field=models.TextField(help_text='Isi berita — mendukung rich text: heading, bold, italic, list, link, dan gambar.'),
        ),
    ]
