# Generated by Django 5.2.17 on 2026-09-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_berita_views_kontak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Berita',
        ),
    ]
