# Generated by Django 5.2.17 on 2026-09-07 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cabang Olahraga',
                'verbose_name_plural': 'Cabang Olahraga',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PerguruanProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Perguruan SIMA', max_length=150)),
                ('tentang', models.TextField(blank=True, help_text='Deskripsi tentang perguruan')),
                ('visi', models.TextField(blank=True)),
                ('misi', models.TextField(blank=True)),
                ('alamat', models.CharField(blank=True, max_length=255)),
                ('kontak', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perguruan/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Perguruan',
                'verbose_name_plural': 'Profil Perguruan',
            },
        ),
        migrations.CreateModel(
            name='AtletProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('kelas_kategori', models.CharField(blank=True, help_text='Contoh: Kelas 55kg / Sabuk Biru / Junior Putra', max_length=100)),
                ('tahun_masuk', models.PositiveIntegerField(blank=True, null=True)),
                ('tinggi_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('berat_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('status_aktif', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atlet/')),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Akun login atlet (dibuat admin). Boleh kosong untuk data awal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet_profile', to=settings.AUTH_USER_MODEL)),
                ('cabor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet', to='atlets.cabor')),
            ],
            options={
                'verbose_name': 'Profil Atlet',
                'verbose_name_plural': 'Profil Atlet',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kejuaraan', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('kota', 'Kota/Kabupaten'), ('provinsi', 'Provinsi'), ('nasional', 'Nasional'), ('internasional', 'Internasional')], default='kota', max_length=15)),
                ('hasil', models.CharField(help_text='Contoh: Juara 1 / Emas / Perak / Perunggu', max_length=100)),
                ('tahun', models.PositiveIntegerField()),
                ('bukti', models.FileField(blank=True, null=True, upload_to='prestasi/')),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestasi', to='atlets.atletprofile')),
            ],
            options={
                'verbose_name_plural': 'Prestasi',
                'ordering': ['-tahun', 'nama_kejuaraan'],
            },
        ),
    ]
