# Generated by Django 5.2.17 on 2026-09-07 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenAtlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Contoh: KTP, KK, Akta Kelahiran, Ijazah, Surat Kesehatan, Sertifikat', max_length=100)),
                ('file', models.FileField(upload_to='dokumen/atlet/%Y/%m/')),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='atlets.atletprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokumen Atlet',
                'verbose_name_plural': 'Dokumen Atlet',
                'ordering': ['-created_at'],
            },
        ),
    ]
