# Generated by Django 5.2.17 on 2026-09-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('latihan_gabungan', 'Latihan Gabungan'), ('tryout', 'Try Out / Uji Tanding'), ('kejuaraan', 'Kejuaraan'), ('rapat', 'Rapat / Pembinaan'), ('lainnya', 'Lainnya')], default='latihan_gabungan', max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('cabor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda', to='atlets.cabor')),
            ],
            options={
                'verbose_name': 'Agenda / Event',
                'verbose_name_plural': 'Agenda / Event',
                'ordering': ['tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='JadwalLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('lokasi', models.CharField(max_length=200)),
                ('pelatih', models.CharField(blank=True, max_length=150)),
                ('kelompok', models.CharField(blank=True, help_text='Contoh: Junior / Senior / Semua', max_length=150)),
                ('keterangan', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('cabor', models.ForeignKey(blank=True, help_text='Kosongkan = berlaku umum/semua cabor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jadwal', to='atlets.cabor')),
            ],
            options={
                'verbose_name': 'Jadwal Latihan',
                'verbose_name_plural': 'Jadwal Latihan',
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
    ]
